import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a0a0a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  brainButton: {
    width: 200,
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1a1a1a',
    borderRadius: 100,
    borderWidth: 2,
    borderColor: '#ff00ff',
    shadowColor: '#ff00ff',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 5,
  },
  brainText: {
    fontSize: 130,
    color: '#fff',
  },
  pointsContainer: {
    position: 'absolute',
    top: 100,
    alignItems: 'center',
  },
  pointsText: {
    fontSize: 70,
    fontWeight: '900',
    color: '#ff00ff',
    fontFamily: 'monospace',
    textShadowColor: '#ff00ff',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  flavorText: {
    position: 'absolute',
    bottom: 100,
    fontSize: 16,
    color: '#00ff00',
    fontFamily: 'monospace',
    textAlign: 'center',
    padding: 10,
  },
  shopButton: {
    position: 'absolute',
    top: 50,
    right: 20,
    backgroundColor: '#1a1a1a',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#ff00ff',
    shadowColor: '#ff00ff',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 5,
  },
  shopButtonText: {
    color: '#ff00ff',
    fontSize: 30,
    fontWeight: 'bold',
    fontFamily: 'monospace',
  },
  // Item Shop Styles
  shopContainer: {
    position: 'absolute',
    alignContent: 'flex-start',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#2a2a2a',
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
    overflow: 'hidden',
  },
  shopHeader: {
    padding: 15,
    backgroundColor: '#333',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  shopContent: {
    flex: 1,
    overflow: 'hidden',
    alignContent: 'flex-start'
  },
  headerContainer: {
    padding: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#2a2a2a',
  },
  itemShopTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#ff00ff',
  },
  pointsAvailable: {
    fontSize: 30,
    color: '#00ff00',
    fontFamily: 'monospace',
    fontWeight: 'bold',
  },
  scrollContainer: {
    padding: 15,
  },
  item: {
    marginBottom: 15,
    borderRadius: 10,
    borderWidth: 1,
    overflow: 'hidden',
  },
  available: {
    backgroundColor: '#2a2a2a',
    borderColor: '#ff00ff',
  },
  unavailable: {
    backgroundColor: '#1a1a1a',
    borderColor: '#ff00ff40',
    opacity: 0.7,
  },
  itemContent: {
    padding: 12,
  },
  itemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 5,
  },
  itemName: {
    fontSize: 20,
    color: '#fff',
    fontFamily: 'monospace',
    fontWeight: 'bold',
  },
  multiplierText: {
    fontSize: 20,
    color: '#ff00ff',
    fontFamily: 'monospace',
    fontWeight: 'bold',
    textShadowColor: '#ff00ff',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 5,
  },
  itemDescription: {
    fontSize: 14,
    color: '#00ff00',
    fontFamily: 'monospace',
    marginBottom: 8,
  },
  itemFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 5,
  },
  itemCost: {
    fontSize: 16,
    fontFamily: 'monospace',
    fontWeight: 'bold',
  },
  costAvailable: {
    color: '#ff00ff',
    textShadowColor: '#ff00ff',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 3,
  },
  costUnavailable: {
    color: '#ff00ff40',
  },
  ownedContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ownedLabel: {
    fontSize: 14,
    color: '#fff',
    fontFamily: 'monospace',
    marginRight: 5,
  },
  ownedCount: {
    fontSize: 16,
    color: '#00ff00',
    fontFamily: 'monospace',
    fontWeight: 'bold',
    textShadowColor: '#00ff00',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 3,
  },
});

export default styles;